[timestep]
fixed = true
max = 0.0004
min = 0.0004

[domain]
min = [-3, -3]
max = [3, 3]
adjustParticle = true
adjustDomain = true

[emitter.drop]
fillDomain = false
min = [-1,-1]
max = [ 1, 1]
velocity = [ 0.0, 0.0]
adjust = false
shape = 'sphere'

[compute]
device='cuda'

[particle]
radius = 0.01

[gravity]
magnitude = 1
pointSource = true


[fluid]
c0 = 10

[simulation]
boundaryScheme = 'solid'
verbose = false
densityScheme = 'continuum'
scheme = 'deltaPlus'

[pressure]
fluidPressureTerm = 'TaitEOS'
boundaryPressureTerm = 'PBSPH'
gamma = 7.0

[diffusion]
velocityScheme = 'deltaSPH'
densityScheme = 'MOG'
alpha = 0.01

[integration]
scheme = 'RK4'
dt = 0.001

[shifting]
enabled = false
scheme = 'deltaPlus'

[kernel]
targetNeighbors = 50

[export]
active = true
prefix = 'oscillating_drop'
staticBoundary = true
interval = 1